# Generated by Django 4.0.4 on 2023-03-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone_num', models.TextField()),
                ('car_num', models.TextField()),
            ],
        ),
    ]
